### ISSUE TITLE
Set player names

### ISSUE THREAD

**Issue by LiamOxley** [RobinStephenson/jbt-2#11]
## Description
Human players must provide a name to act as an identifier before the game begins.

### Client Requirements
2.1 a) v

### Developer Requirements
NA

## Estimated completion time
This issue should be completed in:
2 hours.

**Comment by RobinStephenson** [comment]
@tc975 are you still working on this? if not can you unassign yourself

**Comment by RobinStephenson** [comment]
We can just set the defaults to Player1 and Player2 instead

**Comment by Mart500** [comment]
Will do this within the main menu scene.
