### ISSUE TITLE
Game Termination Conditions

### ISSUE THREAD

**Issue by RobinStephenson** [RobinStephenson/jbt-2#12]
## Description
Game will end in the production phase. #8 
Calculate score based on land and resources owned by player.
Highest scorer wins.
The requirements makes no mention of money counting to score, we should discuss this with the client.

### Client Requirements
2.3

### Developer Requirements
NA

## Estimated completion time
This issue should be completed in:
4 hours

**Comment by LiamOxley** [comment]
Show that the winner becomes Vice Chancellor

**Comment by Mikeywalsh** [comment]
Should be noted that the functions for calculating score and determining a winner already exist and are tested

**Comment by RobinStephenson** [comment]
@Mart500  are you still working on this? if not can you unassign yourself
