### ISSUE TITLE
Auction

### ISSUE THREAD

**Issue by SareenaSingh** [RobinStephenson/jbt-2#14]
**Description**
- Players can auction off resources and purchase resources from other players
- Auction is optional.
- Players should be allowed to purchase from the market during auction phase.
- Players should be able to bid on resources.

**Client Requirements**
2.2.5

**Developer Requirements**

N/A

**Estimated completion time**

This issue should be completed in:

2 days

**Comment by tc975** [comment]
Finished AuctionManager code and started on the UI stuff, but not sure how to continue from here with the UI bits.
