### ISSUE TITLE
Saving and Loading

### ISSUE THREAD

**Issue by tc975** [RobinStephenson/jbt-2#15]
The ability to save a current game and load a saved game.

### Client Requirements
2.8

### Developer Requirements
N/A

### This issue should be completed in:
4 hours

**Comment by Mart500** [comment]
Completed logic in GameHanlder class to save and load
Now need to create UI elements to save and load in the menu

**Comment by Mart500** [comment]
Finished Save and load functions within canvas script and game Handler. Needs UI Additions and jason functions.

**Comment by RobinStephenson** [comment]
Wont be able to do this in time
