### ISSUE TITLE
Auction must be time limited

### ISSUE THREAD

**Issue by SareenaSingh** [RobinStephenson/jbt-2#17]
Description

There should be a time limit placed on the auction

Client Requirements
2.2.5d

Developer Requirements
N/A 

Estimated completion time

This issue should be completed in:

2 hours,

**Comment by RobinStephenson** [comment]
@tc975 assigned you to this and myself as its linked to other issues were working on #14 #9

**Comment by RobinStephenson** [comment]
@tc975 the timeouts are done but youre implementation needs to consider that a player could run out of time part way through your phase
