### ISSUE TITLE
Tooltip hide problems

### ISSUE THREAD

**Issue by tc975** [RobinStephenson/jbt-2#27]
Tooltip box doesn't disappear completely when hide button is clicked, and on some resolutions may not work at all. 

### Client Requirements
N/A
### Developer Requirements
N/A

### This issue should be completed in:
2 hours

**Comment by RobinStephenson** [comment]
@Mikeywalsh did your PR fix this?

**Comment by Mikeywalsh** [comment]
Yeah, should have closed from the PR
