### ISSUE TITLE
Implementation Report

### ISSUE THREAD

**Issue by SareenaSingh** [RobinStephenson/jbt-2#29]
- Explain how your code implements your architecture and requirements
- Briefly explain any significant new features
- Give a systematic report of any significant changes made to the previous software
- State explicitly any of the features required for Assessment 3 that are not (fully) implemented.

(See assessment brief for more detailed information)

Page Limit: 4 pages

**Comment by RobinStephenson** [comment]
closing as we are using google drive to comment on the report
