### ISSUE TITLE
Roboticon customisation bonuses

### ISSUE THREAD

**Issue by LiamOxley** [RobinStephenson/jbt-2#30]
The bonus a roboticon gets from upgrading them, is this done using add or multiplication?

**Comment by RobinStephenson** [comment]
@LiamOxley what was it doing? post the result so everyone can see and we can come back and check later if we forget

**Comment by LiamOxley** [comment]
The system uses addition. My understanding is that the value that each resource is upgraded by is randomly selected between 1 and 4. These are then added to the the current resource values of the roboticon.
