### ISSUE TITLE
Tile Hovering Issue

### ISSUE THREAD

**Issue by SareenaSingh** [RobinStephenson/jbt-2#35]
**Description**

The tile should not still be highlighted in a colour if you are no longer hovering over it. 

**Client Requirements**

N/A

**Developer Requirements**

N/A

**Estimated completion time**

This issue should be completed in:

2 hours

**Comment by RobinStephenson** [comment]
additional issue where if you have a tile selected and you hover over it the hover highlight stays over the last tile you hovered before moving the cursor to the selected tile

**Comment by RobinStephenson** [comment]
mapManagerScript.checkMouseHit is where the logic for this is
