### ISSUE TITLE
When ending a phase, the last selected tile is not interactable for the next player

### ISSUE THREAD

**Issue by Mikeywalsh** [RobinStephenson/jbt-2#48]
## Description
The last selected tile cannot be hovered over until another tile has been selected after a phase has ended

## Steps to reproduce
1. Start a game
2. As player one, select a tile and click end phase
3. As player two, attempt to select the same tile, you cannot
4. You must first select another tile for the previous tile to become interactable again

## Estimated completion time

This issue should be completed in:
1 hour

**Comment by RobinStephenson** [comment]
Good luck the whole tile selection thing is horrible

**Comment by Mikeywalsh** [comment]
I have the power
