### ISSUE TITLE
Production phase actions other than resource production

### ISSUE THREAD

**Issue by RobinStephenson** [RobinStephenson/jbt-2#8]
## Description
Market prices should be set in the production phase. Random events should be started in this phase. Win condition should be checked.

This issue is not for creating the random events etc. but for the implementation of the production phase.

### Client Requirements
2.2.4

### Developer Requirements
Interfaces for events. Win condition checker to be implemented.

## Estimated completion time
This issue should be completed in:
2 hours

**Comment by RobinStephenson** [comment]
random-events branch has added random events to this phase

**Comment by Mikeywalsh** [comment]
This issue has been fixed in a previous pull request. Closing.
